"""Configuration of Beowulf cluster

This script is used by all other scripts
"""

from utilities import NICinfo, Nodeinfo, add2addr
from ethernet_mappings import mac_addr, interface_names

pxeconfig_dir = '/var/lib/tftpboot/pxelinux.cfg'
client_image_dir = '/client_filesystems'
client_system_dirs = ['ubuntu_basesystem']
shared_dir = 'shared'

head_ip = '192.168.11.10'
head_internet_ip = '192.168.10.10'
head_storage_ip = '192.168.20.20'
head_management_ip = '192.168.2.59'
head_hostname = 'alamba'
external_nameserver = '203.77.225.2'
web_ip = '203.77.224.67'
nas_ip = '192.168.20.12'
nfs_permissions = 'rw,no_root_squash,async,no_subtree_check' # For exports on server
netmask = '255.255.255.0'
domain_name = 'aifdr.org'
number_of_nodes = 20 # Nodes will be named as node1, node2, ...

# Filesystems to be used for NFS mount of the NAS
# DO NOT PUT PRECEDING / IN FRONT OF MOUNT POINTS
nas_filesystems = {'/nas1/data': 'scratch_area',
                   '/nas2/data': 'snapshot_area',
                   '/nas3/data': 'model_area',
                   '/nas4/data': 'data_area'}

# List nodes that will be built from the base system.
# Irrespective of this list, all nodes listed in nodes dictionary
# (listed later in this file) will be used in
# server configuration files.


nodes_to_build = ['node1',
                  'node2',
                  'node3',
                  'node4',
                  'node5',
                  'node6',
                  'node7',
                  'node8',
                  'node9',
                  'node10',
                  'node11',
                  'node12',
                  'node13',
                  'node14',
                  'node15',
                  'node16',
                  'node17',
                  'node18',
                  'node19',
                  'node20']

#nodes_to_build = ['node1', 'node2', 'node3', 'node4', 'node5']
#nodes_to_build = ['node6'] #, 'node7']
#nodes_to_build = ['node11', 'node12', 'node13', 'node14', 'node15',
#                  'node16', 'node17', 'node18', 'node19', 'node20']
#nodes_to_build = ['node16', 'node17', 'node18', 'node19', 'node20']
#nodes_to_build = ['node1', 'node2', 'node3', 'node4']

# Define host names of clients and their associated
# IP addresses used by PXE at boot time.
# Macaddresses must be separated by dashes (-) and
# IP addresses by dots (.)
#

# IP addresses for node1
# Other nodes will receive increments
first_net_ip = '192.168.11.11'
first_pxe_ip = '192.168.11.61'
first_nas_ip = '192.168.20.21'

nodes = {}
for i in range(number_of_nodes):
    # Build node info

    nodename = 'node%s' % (i+1)

    NET = NICinfo(mac_addr[nodename]['eth5'],
                  add2addr(first_net_ip, i))

    PXE = NICinfo(mac_addr[nodename]['eth0'],
                  add2addr(first_pxe_ip, i))

    NAS = NICinfo('', # MAC address would be that of bond0 (eth2, eth3), but is not needed
                  add2addr(first_nas_ip, i))

    node = Nodeinfo(pxe=PXE,
                    net=NET,
                    nas=NAS)

    nodes[nodename] = node

#print nodes


auto_generate_disclaimer = '''
# This file was autogenerated by create_pxe_distribution.py
# If you edit this, your modifications will be overwritten
\n
'''


